### ISSUE TITLE
Input images limited to 250 files

### ISSUE THREAD

**Issue by squio** [nathanbain314/mosaic#1]
While executing RunMosaic on Mac OSX Sierra I get an error "too many open files" when the input directory contains more than 250 images.

Is there a way to rise the open files limit?

Example command and error message:

```
./RunMosaic -s 32 -p image.jpg  -i imgs/  -o mosaic.jpg
libc++abi.dylib: terminating with uncaught exception of type vips::VError: vips__file_open_read: unable to open file "imgs/2016-07-12 10.25.15.jpg" for reading
unix error: Too many open files
VipsRegion: valid clipped to nothing
VipsRegion: valid clipped to nothing
VipsRegion: valid clipped to nothing
```

**Comment by squio** [comment]
Additional info: I figured out that the value for max open files is 256 by default as shown by 
  `ulimit -n`. 
Increasing this by issuing a 
  `ulimit -n 2048` 
command before executing the RunMosaic command fixed this issue. So maybe a documentation issue.

Also the format of the input images command is not very fault tolerant. The path needs to end in a slash (eg `imgs/` ) and the program fails when a non-inmage file is in the directory (example: a movie file or even a sub directory).

**Comment by nathanbain314** [comment]
I updated the code to be more tolerant of the image directory name. The program builds a vector of images and then calls arrayjoin to build the mosaic which will fail if the mosaic contains more images than your machine can have open at one time. I had set my ulimit some time ago and forgot about it when I wrote the documentation but I have since updated that.
