### ISSUE TITLE
How to compile on win ?

### ISSUE THREAD

**Issue by VladoPortos** [nathanbain314/mosaic#2]
Hello,
Do you think this could handle 360 000 1920x1080 pictures, putting into one mosaic, zoomable ?

Could you please add small guide how to make it work on windows ?

Regards,
Vlad

**Comment by nathanbain314** [comment]
Yes, this should be able to handle that many images. The most I've ever tested was around 170000, and that took almost ten hours, so be prepared for this to take awhile.
I changed some of the code and build structure to work on windows, and added the directions on the README, so you'll need to download the files again. 
To build on windows, 

Install [mingw-6w4](http://mingw-w64.org/doku.php/download/mingw-builds). At the screen with the various options for installing, choose **x86_64** as the architecture.
Install [cmake](https://cmake.org/download/) , and at the screen where it gives choices adding it to the path, make sure to add it to the system path.
Download the libvips w64 binaries from the vips [download page](https://github.com/jcupitt/libvips/releases) and extract it.
Open up a MinGW-W64 terminal. 
Set an environment variable named **VIPS_INCLUDE** to be the location of the libvips folder and add the binary folder to the system path. 
```
  set VIPS_INCLUDE=C:\Users\nathanbain314\Downloads\vips-dev-w64-all-8.6.3\vips-dev-8.6  
  set PATH=%PATH%;C:\Users\nathanbain314\Downloads\vips-dev-w64-all-8.6.3\vips-dev-8.6\bin  
```
Then compile the progam. 
```
  cmake . -G "MinGW Makefiles"   
  mingw32-make  
```

**Comment by VladoPortos** [comment]
Thanks a lot, I got stuck on "Open up a MinGW-W64 terminal." which one is that ? there is 49 exe files in C:\Program Files\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\mingw64\bin

**Comment by VladoPortos** [comment]
managed to get it work, manually adding vips-dev-8.6\bin  to paths + mingw64\bin into paths and crating variable VIPS_INCLUDE than it compiled ok... doing to give it a try tonight :) ( aslo 10 hours is nothing... I have with one mosaic program running this project now for 40hours and its only at 60% ! :D )

**Comment by VladoPortos** [comment]
Ach no luck :( when I run it I get this error: https://i.imgur.com/2Ti9a9t.jpg

**Comment by nathanbain314** [comment]
That is an interesting error that I have not seen before. I am going to look into it some more, but I did notice a few things that could be wrong.  
It looks like you might be using a different command line than the mingw-w64 terminal. This should be a Windows Batch File called **mingw-w64** located in the C:\Program Files\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\ directory. Also if you open up the search function and type in "mingw" the first result should be the terminal.  
You appear to be running the command from the system32 directory. I don't use windows very often but this might be a protected directory. Also when you open the html file to view the zoomable mosaic, you will want the js directory to be in the same directory.  
-n, the number of tiles horizontally, is set to 10000, which is large number. This number can not be larger than the number of horizontal pixels. However, if you have a large image then this should work fine.

**Comment by VladoPortos** [comment]
You are right, the issue is I was running it from normal windows terminal. I went to start and typed mingw-w64 and second option that was shown was called just "Terminal" so I tried that and it run the correct terminal.  I have tried to run the RunMosaic there and it seems to be working, at least it is now showing Found XXXX Images... and no error.

I'm curious, my goal is to put all 360 000 pictures into zoomable mosaic ( preferably based on some picture ) but that seems to be impossible :D as I did not understand that -n should be max horizontal size ( in pixels ) of the image I'm basing the mosaic on. 

If I'm calculating this correctly, I would need base image of resolution 40 000px x 30 000px to fit in 360 000 pictures. Maybe I have set too high goals for me :D ( I was doing analysis of most used colors on .sk domain web pages, so I made snap shot (1920x1080) of all 366 000 of them, run custom script to analyze 10 most dominant colors in each and from that I got what I was after... but wanted if there is possible to display all that pictures in one / zoomable format just for fun, something like google maps do... )

**Comment by nathanbain314** [comment]
I'm glad to hear that you got the program running.

-n is the number of square tiles from left to right. If you want 360000 tiles and your image was square then you would want -n to be 600 and the image could be as small as 600x600 pixels. If you had a 16:9 image -n should be 800 with 800x450 being the smallest possible resolution. If you want to fit 360000 images in a mosaic then you will probably want more than the minimum number of tiles, so maybe set -n to somewhere between 1000-2000.

A larger resolution base image will match the shapes of the input images and tiles more closely, while a lower resolution image will match the average color of the image.  
The tiles in the output zoomable image will be as large as possible and won't change based on the resolution of the base image. The base image is only used to generate the mosaic and only needs to be large enough to hold the tiles. If you want the tiles to match individual shapes in the base image then you will need a large image. However, since you are using webpages as the input images, then average colors should work better, so you will probably want a lower resolution image, or just set -m to 1 and let it shrink the base image for you. 

The program will use the best image for each tile repeating as often as it needs to, so it might only use 10000 out of 360000 images. You can see how many images were used by looking at the number of .dzi files in the zoom directory of the output directory.
You can force it to use more images with -r. -r is the smallest number of tiles that can separate repeated images. So if -r is set to 300, then an image will be used only once in any 601x601 tile block, and at least 361201 different images will have to be used. This can create an impressive output built from very many images. however, since the program won't be using the best possible tile, the output might look worse. -r also increases the time it takes to build the mosaic.

Here is an example of running it with -r set to 4, 8, and 16 with 1100 input images. The third result uses more input images but the colors do not match the base image as closely. This might look different with 360000 images, so you might want to keep -r below 150, but just play around with the settings until you get something that looks good and uses enough images.
![repeat](https://user-images.githubusercontent.com/10777056/37327205-579c38f6-2663-11e8-8f76-ebe4c4b5e7f5.png)

**Comment by VladoPortos** [comment]
you are a legend ! thanks a lot for help. I did generate mosaic today successfully, but as you say I need to specify so it repeat minimally, running that now :)

**Comment by VladoPortos** [comment]
Uf I run the program as this:
`RunMosaic.exe -p E:\pony.jpg -d E:\SK_Internet -n 1500 -m 1 -r 300 -o E:\sk_mosaic`

It did detected correctly 366598 images, then done 100% Processing images... but after 10hours ( and usage of 80%CPU ) it did not move beyond 0.0% of Build mosaic ... not sure if the parameters are too much for it. ( the -p image is 2560x1440 image )

**Comment by nathanbain314** [comment]
I pushed some new code onto the repository, so you will need to download this and compile it again. The mosaic generates much faster than it previously did with large values of -r, but it will slow down as the mosaic generation progresses.  
However, -r 300 is still pretty large. I timed it with an image of the same size, -r 200, and more than 160000 input images, and it has not completed, but it started out at 0.01 seconds per tile, and slowed down to 0.5 seconds per tile at 10% completion, so it might take an entire week to finish. If you have a more powerful computer or don't mind waiting a while, then you could generate it completely. Otherwise you might want to lower -r to 150 or lower.

**Comment by VladoPortos** [comment]
Thanks, I ended up just renting virtual server for a month, to have it done... cause on local computer its taking ages and I need to used it :D

**Comment by nathanbain314** [comment]
Ok, thats a good idea. The program is multithreaded, so since you are renting a server you could get a 4 or 8 core machine and speed it up a bit.

**Comment by nathanbain314** [comment]
I pushed some new code onto the repository that you might want to use. It makes -r run at almost a constant speed, so -r 300 might only take a few hours.

**Comment by VladoPortos** [comment]
cool, I'll give it a try. I'm curious if I use picture that 2560px wide should I use -n 2560 ? ( also is there a way that in the finish mosaic the pictures are not squared since originals are 1920x1080 I would not mind if it would made it smaller, just kept the ratio, not sure if that is possible though.

**Comment by nathanbain314** [comment]
It does not matter what -n is as long as it is less than or equal to the image width. However, 2560 is 1.7 times larger than 1500, so it will take about 3 times as long to generate and up to 3 times as much disk space. If you don't mind the extra time and disk space then go ahead and use that, or 2000, or any number <= 2560.  
The tiles have to be square. It is hardcoded into the program, and is the only way the full resolution mosaic can work. The full resolution mosaic reuses as many square tiles as possible in order to save disk space. A 2560x1440 mosaic of 1080x1080 images would be a 4.3 terapixel image, which would take up a lot of disk space, but the program will generate a mosaic that takes up much less space. Since you are using a large -r, it might not save too much space, but it will use much less memory since it won't generate a 4.3 terapixel in memory, but will instead build it peice by peice.  
I might add the ability to use different shaped tiles later, but it won't be able to have the memory and storage benefits of the square tile mosaic.

**Comment by nathanbain314** [comment]
I updated the code to use custom tile shapes. Just set -m to be the width of the tile for the mosaic and set -l (lowercase L) to be the height of the mosaic tile, and then -i to be the width of the tile in the image. So -m 2 -l 1 -i 100 will use a 2x1 pixel tile to generate the mosaic and then build the image out of 100x50 pixel tiles. You could also use -m 16 -l 9 -i 96 so that it better represents the shape of the 1920x1080 images. 
I also got the zoomable image to not use a lot of memory, so you can set -i to as large as you want, as long as the input images are at least (-i) x (-i * -l / -m) pixels. A custom tile shape will still use much more disk space than a square tile mosaic, so you probably dont want -i to be too large.

**Comment by VladoPortos** [comment]
Fantastic ! I'll give it a try, will have to let it run now for some time, but as soon as I got the results I share them here ;)

**Comment by nathanbain314** [comment]
Hey, did you get the mosaic to work correctly? And if you did, would you mind if I post the picture or a link to the zoomable on the wiki?

**Comment by VladoPortos** [comment]
Hello, while it was working the server crashed ( not because of it, I think, different issue) and ended up doing it my self with python and pyvips module, result of that is deepzoom.reverz.sk and using another program Adnrea Mosaic I ended up with pony.reverz.sk

**Comment by nathanbain314** [comment]
Ok, thanks for the feedback.
